### ISSUE TITLE
iPhone 5C and iOS 7 simulator issues

### ISSUE THREAD

**Issue by crazyjooe** [rollout/rollout.io-ios#17] opened 2015-01-23 20:20 UTC
When running app with rollout integration on 5C device, I get the following error:
```
 ld: don't know how to convert branch instruction fedc8707 referencing _objc_storeStrong.island to bx in '-[RolloutDynamic initWithInvocationsListFactory:rolloutErrors:]' from /Users/crazyjoe/Library/Developer/Xcode/DerivedData/askfm-grmpfusrmwsandbgvrvalcugmivr/Build/Intermediates/askfm.build/Debug-iphoneos/askfm.build/Objects-normal/armv7/RolloutDynamic.o for architecture armv7 
```

Time after time files might change, just pasted the latest one.
It works fine on newer devices like iPhone 5s, however.

**Comment by ekeren** [comment] 2015-01-25 08:41
@crazyjooe this is already reported on #16 . But this issue should remain open because we didn't find the root cause yet. 

Please contact me at eyal@rollout.io so I can extract some debugging information from your environment so quickly reach the bottom of this.

**Comment by ekeren** [comment] 2015-02-01 11:22
This issue was resolved locally for @crazyjooe , by cleaning the entire build folder. 
We are still investigating the root cause

**Comment by ekeren** [comment] 2015-02-07 15:35
closing this issue, #16 remains open

**Closed by ekeren** 2015-02-07 15:35 UTC
Labels: duplicate
