### ISSUE TITLE
Arc forbids Objective-C objects in structs

### ISSUE THREAD

**Issue by natanrolnik** [rollout/rollout.io-ios#66] opened 2015-10-25 22:17 UTC
In my RolloutDynamic_structs.h file, I have the following:

```
typedef struct __rollout_dummy_struct__aRnh6L44JYFjIPDWNRS_Sz8G$m4 {
  id iOS;
  id tvOS;
  id watchOS;
  type;
} __rollout_dummy_struct__aRnh6L44JYFjIPDWNRS_Sz8G$m4;
```

This leads to a compiler error, that "Arc forbids Objective-C objects in structs".

I temporarily fixed it with the following code:

```
typedef struct __rollout_dummy_struct__aRnh6L44JYFjIPDWNRS_Sz8G$m4 {
  __unsafe_unretained id iOS;
  __unsafe_unretained id tvOS;
  __unsafe_unretained id watchOS;
  __rollout_enum type;
} __rollout_dummy_struct__aRnh6L44JYFjIPDWNRS_Sz8G$m4;
```

Any idea how to fix that? Happened after updating to Xcode 7.1

**Comment by silyevsk** [comment] 2015-10-26 10:05
Thanks for letting us know! It's a bug in our auto-generated code. Hopefully, we will fix it in v0.11 (will be released in about a week)

**Comment by natanrolnik** [comment] 2015-10-26 10:26
Great, thanks!

**Comment by natanrolnik** [comment] 2015-11-04 12:15
Hi @silyevsk ! Any updates on this issue?

**Comment by silyevsk** [comment] 2015-11-04 15:18
Hi Natan,

We've fixed it in 0.11 indeed, but it takes more time to release this version. I hope it will happen during the next week.

The workaround you are using is absolutely fine though, we actually fixed the issue in the same way.

**Comment by natanrolnik** [comment] 2015-11-05 09:27
Cool! I fixed it this way, but the only thing is that sometimes (and I don't know when exactly), this file is regenerated, and I need to fix every time.

**Comment by silyevsk** [comment] 2015-11-23 08:22
0.11 was released yesterday, the issue is fixed there.

**Closed by silyevsk** 2015-11-23 08:22 UTC

**Comment by natanrolnik** [comment] 2015-11-23 09:45
Great, thanks!

**Comment by natanrolnik** [comment] 2015-11-23 15:06
Btw, is there a changelog somewhere?

**Comment by clooth** [comment] 2015-11-30 10:44
Oh wow I was just googling about this error. Hadn't updated in a while :)
