### ISSUE TITLE
Hot-patch method by name

### ISSUE THREAD

**Issue by silyevsk** [rollout/rollout.io-ios#74] opened 2015-12-22 09:49 UTC
Similarly to polyfills, there should be an ability to patch just any method by providing its class, selector and signature.

**Comment by bfcatch** [comment] 2016-05-02 07:48
+1

**Comment by ekeren** [comment] 2016-07-31 15:45
This is duplicate of #1, and the functionality is already available

Look for the custom hot-patch link above the search box

**Closed by ekeren** 2016-07-31 15:45 UTC
